# generated by datamodel-codegen:
#   filename:  recipe-inputs.openapi.json

from __future__ import annotations

from datetime import date
from typing import Any
from uuid import UUID

from pydantic import (
    UUID4,
    AwareDatetime,
    ConfigDict,
    Field,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
)
from pydantic import BaseModel as _BaseModel


class BaseModel(_BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )


class CreateIngredientFoodAlias(BaseModel):
    name: StrictStr


class CreateIngredientFoodSubstitution(BaseModel):
    substituteFoodId: UUID4 | None = None
    note: StrictStr | None = None


class CreateIngredientUnitAlias(BaseModel):
    name: StrictStr


class CreateRecipe(BaseModel):
    name: StrictStr


class IngredientFoodAlias(BaseModel):
    name: StrictStr


class IngredientFoodSummary(BaseModel):
    id: UUID4
    name: StrictStr
    pluralName: StrictStr | None = None


class IngredientReferences(BaseModel):
    referenceId: UUID4 | None = None


class IngredientUnitAlias(BaseModel):
    name: StrictStr


class MultiPurposeLabelSummary(BaseModel):
    name: StrictStr
    color: StrictStr = "#959595"
    groupId: UUID4
    id: UUID4


class NoteReference(BaseModel):
    referenceId: UUID4 | None = None


class Nutrition(BaseModel):
    calories: StrictStr | None = None
    carbohydrateContent: StrictStr | None = None
    cholesterolContent: StrictStr | None = None
    fatContent: StrictStr | None = None
    fiberContent: StrictStr | None = None
    proteinContent: StrictStr | None = None
    saturatedFatContent: StrictStr | None = None
    sodiumContent: StrictStr | None = None
    sugarContent: StrictStr | None = None
    transFatContent: StrictStr | None = None
    unsaturatedFatContent: StrictStr | None = None


class RecipeAsset(BaseModel):
    name: StrictStr
    icon: StrictStr
    fileName: StrictStr | None = None


class RecipeCategory(BaseModel):
    id: UUID4 | None = None
    groupId: UUID4 | None = None
    name: StrictStr
    slug: StrictStr
    recipeCount: StrictInt = 0


class RecipeIngredientSubstitution(BaseModel):
    substituteFoodId: UUID4 | None = None
    note: StrictStr | None = None
    substituteFood: IngredientFoodSummary | None = None


class RecipeNote(BaseModel):
    title: StrictStr
    text: StrictStr
    referenceId: UUID | None = None


class RecipeSettings(BaseModel):
    public: StrictBool = False
    showNutrition: StrictBool = False
    showAssets: StrictBool = False
    landscapeView: StrictBool = False
    disableComments: StrictBool = True
    locked: StrictBool = False


class RecipeStep(BaseModel):
    id: UUID | None = None
    title: StrictStr | None = ""
    summary: StrictStr | None = ""
    text: StrictStr
    ingredientReferences: list[IngredientReferences] = Field([], validate_default=True)
    noteReferences: list[NoteReference] = Field([], validate_default=True)


class RecipeTag(BaseModel):
    id: UUID4 | None = None
    groupId: UUID4 | None = None
    name: StrictStr
    slug: StrictStr
    recipeCount: StrictInt = 0


class RecipeTool(BaseModel):
    id: UUID4
    groupId: UUID4 | None = None
    name: StrictStr
    slug: StrictStr
    recipeCount: StrictInt = 0
    householdsWithTool: list[StrictStr] = []


class UserBase(BaseModel):
    id: UUID4
    username: StrictStr | None = None
    admin: StrictBool
    fullName: StrictStr | None = None


class CreateIngredientFood(BaseModel):
    id: UUID4 | None = None
    name: StrictStr
    pluralName: StrictStr | None = None
    description: StrictStr = ""
    extras: dict[str, Any] | None = {}
    labelId: UUID4 | None = None
    aliases: list[CreateIngredientFoodAlias] = Field([], validate_default=True)
    substitutions: list[CreateIngredientFoodSubstitution] = Field(
        [], validate_default=True
    )
    householdsWithIngredientFood: list[StrictStr] = []


class CreateIngredientUnit(BaseModel):
    id: UUID4 | None = None
    name: StrictStr
    pluralName: StrictStr | None = None
    description: StrictStr = ""
    extras: dict[str, Any] | None = {}
    fraction: StrictBool = True
    abbreviation: StrictStr = ""
    pluralAbbreviation: StrictStr | None = ""
    useAbbreviation: StrictBool = False
    aliases: list[CreateIngredientUnitAlias] = Field([], validate_default=True)
    standardQuantity: StrictFloat | None = None
    standardUnit: StrictStr | None = None


class IngredientFoodSubstitution(BaseModel):
    substituteFoodId: UUID4 | None = None
    note: StrictStr | None = None
    substituteFood: IngredientFoodSummary | None = None


class IngredientUnit(BaseModel):
    id: UUID4
    name: StrictStr
    pluralName: StrictStr | None = None
    description: StrictStr = ""
    extras: dict[str, Any] | None = {}
    fraction: StrictBool = True
    abbreviation: StrictStr = ""
    pluralAbbreviation: StrictStr | None = ""
    useAbbreviation: StrictBool = False
    aliases: list[IngredientUnitAlias] = Field([], validate_default=True)
    standardQuantity: StrictFloat | None = None
    standardUnit: StrictStr | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class RecipeCommentOut(BaseModel):
    id: UUID4
    recipeId: UUID4
    text: StrictStr
    createdAt: AwareDatetime
    userId: UUID4
    user: UserBase
    updatedAt: AwareDatetime


class IngredientFood(BaseModel):
    id: UUID4
    name: StrictStr
    pluralName: StrictStr | None = None
    description: StrictStr = ""
    extras: dict[str, Any] | None = {}
    labelId: UUID4 | None = None
    aliases: list[IngredientFoodAlias] = Field([], validate_default=True)
    substitutions: list[IngredientFoodSubstitution] = Field([], validate_default=True)
    householdsWithIngredientFood: list[StrictStr] = []
    label: MultiPurposeLabelSummary | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class Recipe(BaseModel):
    id: UUID4 | None = None
    userId: UUID4 | None = None
    householdId: UUID4 | None = None
    groupId: UUID4 | None = None
    name: StrictStr | None = None
    slug: StrictStr = ""
    image: Any = None
    recipeServings: StrictFloat = 0
    recipeYieldQuantity: StrictFloat = 0
    recipeYield: StrictStr | None = None
    totalTime: StrictStr | None = None
    prepTime: StrictStr | None = None
    cookTime: StrictStr | None = None
    performTime: StrictStr | None = None
    description: StrictStr | None = ""
    recipeCategory: list[RecipeCategory] | None = Field([], validate_default=True)
    tags: list[RecipeTag] | None = Field([], validate_default=True)
    tools: list[RecipeTool] = Field([], validate_default=True)
    rating: StrictFloat | None = None
    orgURL: StrictStr | None = None
    dateAdded: date | None = None
    dateUpdated: AwareDatetime | None = None
    createdAt: AwareDatetime | None = None
    lastMade: AwareDatetime | None = None
    recipeIngredient: list[RecipeIngredient] = Field([], validate_default=True)
    recipeInstructions: list[RecipeStep] | None = Field([], validate_default=True)
    nutrition: Nutrition | None = None
    settings: RecipeSettings | None = None
    assets: list[RecipeAsset] | None = Field([], validate_default=True)
    notes: list[RecipeNote] | None = Field([], validate_default=True)
    extras: dict[str, Any] | None = {}
    comments: list[RecipeCommentOut] | None = Field([], validate_default=True)
    updatedAt: AwareDatetime | None = None


class RecipeIngredient(BaseModel):
    quantity: StrictFloat | None = 0
    unit: IngredientUnit | CreateIngredientUnit | None = Field(
        None,
        description="An existing IngredientUnit record from lookup, or a CreateIngredientUnit object. A bare ID is not accepted.",
    )
    food: IngredientFood | CreateIngredientFood | None = Field(
        None,
        description="An existing IngredientFood record from lookup, or a CreateIngredientFood object. A bare ID is not accepted.",
    )
    referencedRecipe: Recipe | None = None
    note: StrictStr | None = ""
    display: StrictStr = ""
    title: StrictStr | None = Field(
        None,
        description="Ingredient section heading (for example Sauce), not the ingredient text. Use food, note and originalText for the ingredient itself.",
    )
    originalText: StrictStr | None = None
    substitutions: list[RecipeIngredientSubstitution] = Field([], validate_default=True)
    referenceId: UUID | None = None


Recipe.model_rebuild()
